### ISSUE TITLE
hi.  you can do this more simply

### ISSUE THREAD

**Issue by mattbezark** [SimonFairbairn/MKAnnotationViewWithAutoLayout#1]
hi,

at least now, you can do this without the extra effort.  see this post:

https://gist.github.com/xavierjurado/36831db07b55e0e3479f

**Comment by SimonFairbairn** [comment]
I'm not sure you understand what it was I was going for. The primary purpose was to have reusable views work with Storyboards/Interface Builder. Your code doesn't seem to allow for that, unless I'm missing something?
